import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const source=ts.createSourceFile('settings.tsx',fs.readFileSync(new URL('../app/settings.tsx',import.meta.url),'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
function load(name,env){let node;function visit(n){if(ts.isFunctionDeclaration(n)&&n.name?.text===name)node=n;ts.forEachChild(n,visit)}visit(source);assert(node);const code=ts.transpileModule(`const action=(${node.getText(source)});`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;return new Function(...Object.keys(env),code+'; return action;')(...Object.values(env));}
test('logout cleanup awaits personal then legacy cancellation and reports failures',async()=>{const calls=[];let reject=false;const fn=load('clearRemindersBeforeExit',{user:{id:'a'},cancelPersonalRemindersForLogout:async()=>{calls.push('personal');if(reject)throw Error('OS failure')},cancelPushRegistration:async id=>calls.push(id),Alert:{alert:()=>calls.push('alert')},t:x=>x});assert.equal(await fn(),true);assert.deepEqual(calls,['personal','a']);calls.length=0;reject=true;assert.equal(await fn(),false);assert.deepEqual(calls,['personal','alert']);});
test('failed reminder cleanup prevents signout and remote token mutation',async()=>{let touched=false;const fn=load('handleSignOut',{clearRemindersBeforeExit:async()=>false,user:{id:'a'},supabase:{from:()=>{touched=true},auth:{signOut:async()=>{touched=true}}},Alert:{alert(){}},t:x=>x});await fn();assert.equal(touched,false);});
test('account deletion waits for cleanup and preserves account on failure',async()=>{let confirm;let deleted=false;const busy=[];const fn=load('handleDeleteAccount',{Alert:{alert:(_t,_b,buttons)=>{if(buttons)confirm=buttons[1].onPress}},t:x=>x,setDeletingAccount:x=>busy.push(x),clearRemindersBeforeExit:async()=>false,supabase:{rpc:async()=>{deleted=true},auth:{signOut:async()=>{deleted=true}}}});fn();await confirm();assert.equal(deleted,false);assert.deepEqual(busy,[true,false]);});
