export const content = {
  en: {
    title: 'Care without giving cash', kicker: 'FREE • COMPLETE GUIDED PRACTICE',
    intro: 'Practice a money-request conversation at your own pace. This is a written, fictional exercise—not a live conversation or personalized clinical advice. No audio is recorded. No purchase, trial, or automatic billing.',
    privacy: 'Progress and optional wording stay in this account’s storage on this device. They are not sent by this exercise. Avoid names or sensitive details; anyone with access to this account and device may read them.',
    urgent: 'Need urgent support? Free help now', safety: 'If there is immediate danger, stop practicing and contact local emergency services. You do not need to finish this exercise to get help.',
    steps: [
      { title: '1. Name care and your limit', prompt: 'Your loved one says: “Can you send me money? I need it tonight.” You want to be caring without giving cash.', options: [
        { reply: 'I care about you. I’m not able to give you cash. I can talk with you about what you need.', why: 'Care and a limit can sit in the same sentence. Naming what you can do avoids turning the boundary into rejection. You do not have to prove how the money would be used or win an argument to set your own limit.', response: '“So you don’t trust me?”' },
        { reply: 'I’m worried and need a moment before we talk about money. I won’t send cash tonight.', why: 'A pause can keep urgency from making the decision for you. The clear limit prevents “a moment” from sounding like a promise of money later. Take the time you need; a request does not obligate an immediate answer.', response: '“There’s no time. I thought you would help.”' },
      ] },
      { title: '2. Respond to pressure without debating', prompt: 'The reply may bring guilt or doubt. Practice acknowledging the feeling without giving up your limit.', options: [
        { reply: 'I hear that you’re upset. I care about you, and my answer about cash is still no.', why: 'Acknowledging emotion is not agreement with every accusation. Repeating a short limit avoids adding explanations that can become new arguments. You can be disappointed by their reaction and still make a decision about your own money.', response: '“Then what are you willing to do?”' },
        { reply: 'I want to understand what you need. I’m not going to argue about trust or send cash.', why: 'This brings the conversation back to a concrete need rather than defending your character. Curiosity does not commit you to paying. If the conversation becomes threatening, end the exercise and use the free support link instead.', response: '“I need food and a ride.”' },
      ] },
      { title: '3. Offer only what you can sustain', prompt: 'Choose a realistic next step. Offering an alternative is optional; do not promise resources or contact you cannot safely provide.', options: [
        { reply: 'If you want, I can help look for food or transportation options. I’m not offering cash. We can check in tomorrow.', why: 'A specific, limited offer leaves the other person free to accept or decline. Make it only if it fits your budget, time, and safety. You are not responsible for controlling the outcome, and a useful boundary does not depend on a grateful response.', response: '“I don’t like it, but send me the options.” They might also decline; your boundary can remain the same.' },
        { reply: 'I can’t offer money or arrange anything tonight. I care about you. I’m going to pause this conversation now.', why: 'You do not have to replace every “no” with another task. A respectful ending protects your capacity without threatening punishment. Only suggest a later check-in if you genuinely want and are able to follow through.', response: '“Fine.” A quiet or unhappy ending does not mean you failed. Give yourself space before deciding what comes next.' },
      ] },
    ],
    next: 'Keep practicing', finish: 'Complete practice & keep my take-away', back: 'Previous step', optional: 'My own wording (optional)', placeholder: 'Use words that sound like you…', explanation: 'Why this can help', reply: 'A possible reply', completed: 'Your take-away — yours to keep', summary: 'You practiced care, a clear limit, and a next step you control. These words cannot guarantee someone else’s response. Read them slowly, adapt them, and use them only when it feels safe.', saved: 'Saved on this device', save: 'Save my wording', loading: 'Loading your practice…', error: 'We could not load or save your practice. Your saved progress has not been intentionally replaced. Retry, or explicitly reset it below.', retry: 'Retry', reset: 'Reset this practice', confirm: 'Delete saved choices and wording on this device?', cancel: 'Cancel', signIn: 'Sign in to keep this practice separate from other accounts.', exit: 'Back', review: 'Review my responses', saving: 'Saving…',
  },
  es: {
    title: 'Cuidar sin dar dinero', kicker: 'GRATIS • PRÁCTICA GUIADA COMPLETA',
    intro: 'Practica a tu ritmo una conversación sobre una petición de dinero. Es un ejercicio escrito y ficticio, no una conversación en vivo ni consejo clínico personalizado. No se graba audio. Sin compra, prueba ni cobro automático.',
    privacy: 'El progreso y tus palabras opcionales se guardan para esta cuenta en este dispositivo. Este ejercicio no los envía. Evita nombres y datos sensibles; alguien con acceso a esta cuenta y dispositivo podría leerlos.',
    urgent: '¿Necesitas apoyo urgente? Ayuda gratuita ahora', safety: 'Si hay peligro inmediato, deja la práctica y contacta a los servicios de emergencia locales. No necesitas terminar el ejercicio para recibir ayuda.',
    steps: [
      { title: '1. Expresa cariño y tu límite', prompt: 'Tu ser querido dice: «¿Me mandas dinero? Lo necesito esta noche». Quieres mostrar cariño sin dar efectivo.', options: [
        { reply: 'Me importas. No puedo darte efectivo. Puedo hablar contigo sobre lo que necesitas.', why: 'El cariño y un límite pueden estar en la misma frase. Decir qué sí puedes hacer evita que el límite sea un rechazo personal. No tienes que demostrar cómo se usaría el dinero ni ganar una discusión para decidir sobre tus recursos.', response: '«¿Entonces no confías en mí?»' },
        { reply: 'Estoy preocupado y necesito un momento antes de hablar de dinero. No enviaré efectivo esta noche.', why: 'Una pausa evita que la urgencia decida por ti. El límite claro impide que «un momento» suene a una promesa de dinero después. Puedes tomarte tiempo: una petición no te obliga a responder de inmediato.', response: '«No hay tiempo. Pensé que me ayudarías».' },
      ] },
      { title: '2. Responde a la presión sin discutir', prompt: 'La respuesta puede provocar culpa o dudas. Practica reconocer la emoción sin abandonar tu límite.', options: [
        { reply: 'Entiendo que estés molesto. Me importas, y mi respuesta sobre el efectivo sigue siendo no.', why: 'Reconocer una emoción no significa aceptar cada acusación. Repetir un límite breve evita dar explicaciones que abran nuevas discusiones. Puedes sentir tristeza por su reacción y mantener tu decisión sobre tu dinero.', response: '«¿Entonces qué estás dispuesto a hacer?»' },
        { reply: 'Quiero entender qué necesitas. No voy a discutir sobre la confianza ni enviar efectivo.', why: 'Esto vuelve a una necesidad concreta en lugar de defender tu carácter. Preguntar no te compromete a pagar. Si la conversación se vuelve amenazante, deja el ejercicio y usa el enlace de apoyo gratuito.', response: '«Necesito comida y transporte».' },
      ] },
      { title: '3. Ofrece solo lo que puedes sostener', prompt: 'Elige un siguiente paso realista. Ofrecer alternativas es opcional; no prometas recursos ni contacto que no puedas brindar con seguridad.', options: [
        { reply: 'Si quieres, puedo ayudarte a buscar opciones de comida o transporte. No ofrezco efectivo. Podemos hablar mañana.', why: 'Una oferta concreta y limitada permite que la otra persona acepte o no. Hazla solo si encaja con tu presupuesto, tiempo y seguridad. No eres responsable de controlar el resultado; tu límite no depende de que te lo agradezcan.', response: '«No me gusta, pero mándame las opciones». También podría negarse; tu límite puede mantenerse.' },
        { reply: 'No puedo ofrecer dinero ni organizar nada esta noche. Me importas. Ahora voy a pausar esta conversación.', why: 'No tienes que sustituir cada «no» por otra tarea. Terminar con respeto protege tu capacidad sin amenazar con castigos. Propón hablar más tarde solo si realmente quieres y puedes cumplirlo.', response: '«Está bien». Un final silencioso o incómodo no significa que hayas fallado. Date espacio antes de decidir qué sigue.' },
      ] },
    ],
    next: 'Seguir practicando', finish: 'Completar y guardar mi resumen', back: 'Paso anterior', optional: 'Mis propias palabras (opcional)', placeholder: 'Escribe como tú hablarías…', explanation: 'Por qué puede ayudar', reply: 'Una posible respuesta', completed: 'Tu resumen: para conservar', summary: 'Practicaste cariño, un límite claro y un siguiente paso que tú controlas. Estas palabras no garantizan la respuesta de otra persona. Léelas despacio, adáptalas y úsalas solo cuando sea seguro.', saved: 'Guardado en este dispositivo', save: 'Guardar mis palabras', loading: 'Cargando tu práctica…', error: 'No pudimos cargar o guardar la práctica. No hemos reemplazado intencionalmente tu progreso guardado. Reintenta o restablécelo explícitamente abajo.', retry: 'Reintentar', reset: 'Restablecer esta práctica', confirm: '¿Borrar las elecciones y palabras guardadas en este dispositivo?', cancel: 'Cancelar', signIn: 'Inicia sesión para guardar esta práctica separada de otras cuentas.', exit: 'Volver', review: 'Revisar mis respuestas', saving: 'Guardando…',
  },
};
