// Legacy fallback for confirmation emails generated by older app builds.
// Supabase's default Edge Function domain renders HTML as plain text, so this
// function redirects to the normal Sober Helpline website instead.
const CONFIRMED_URL = 'https://soberhelpline.com/app-confirmed.html';

Deno.serve(() => Response.redirect(CONFIRMED_URL, 302));
