export const membershipGuideContent = {
  en: {
    title: 'Guidance for the family—not control over your loved one',
    introLabel: 'A written introduction',
    intro: 'Matt Brown is the founder of Sober Helpline and an interventionist with 22 years of experience. Family coaching helps you think through boundaries, communication, and your next practical step. You do not have to control someone else’s choices to care for yourself.',
    safety: 'If someone is in immediate danger, call your local emergency number (911 in the U.S.). Do not wait for a coaching reply. Coaching is not emergency care, diagnosis, or medical treatment and cannot guarantee sobriety.',
    urgent: 'Free urgent-help guidance',
    wallet: 'Free emergency contacts · Safety Wallet',
    practice: 'Try the free practice',
    exampleTitle: 'Illustrative example—not a real conversation',
    exampleNote: 'Written to explain coaching. Not a testimonial or an actual message from Matt. Nothing here is sent to a coach.',
    questionLabel: 'Example family question',
    question: 'My adult son asks for money again. How can I say no without starting another argument?',
    responseLabel: 'Example coaching response',
    response: 'Start with what you can choose: a boundary you can keep. You could say, “I care about you. I am not giving cash. I can help you look at other options.” You do not need to persuade him to agree. If the conversation feels unsafe, step away and seek help.',
    options: 'What support looks like',
    timing: 'Essential messaging is for nonurgent questions, not live chat. There is no fixed response-time guarantee. Premier private video must be scheduled and is subject to availability.',
    compare: 'Compare memberships in Support',
    signedIn: 'Review options for your account in Support. Opening this page does not change your membership.',
    signedOut: 'You can read this guide without subscribing. Support shows membership options and account steps.',
    prices: 'Current store subscription prices',
  },
  es: {
    title: 'Orientación para la familia, no control sobre tu ser querido',
    introLabel: 'Una introducción escrita',
    intro: 'Matt Brown es el fundador de Sober Helpline y un intervencionista con 22 años de experiencia. El coaching familiar te ayuda a pensar en límites, comunicación y tu próximo paso práctico. No tienes que controlar las decisiones de otra persona para cuidar de ti.',
    safety: 'Si alguien está en peligro inmediato, llama al número local de emergencias (911 en EE. UU.). No esperes una respuesta del coach. El coaching no es atención de emergencia, diagnóstico ni tratamiento médico, y no puede garantizar la sobriedad.',
    urgent: 'Orientación urgente gratuita',
    wallet: 'Contactos de emergencia gratuitos · Safety Wallet',
    practice: 'Prueba la práctica gratuita',
    exampleTitle: 'Ejemplo ilustrativo: no es una conversación real',
    exampleNote: 'Escrito para explicar el coaching. No es un testimonio ni un mensaje real de Matt. Aquí no se envía nada a un coach.',
    questionLabel: 'Ejemplo de pregunta familiar',
    question: 'Mi hijo adulto vuelve a pedirme dinero. ¿Cómo puedo decir que no sin empezar otra discusión?',
    responseLabel: 'Ejemplo de respuesta de coaching',
    response: 'Empieza por lo que tú puedes elegir: un límite que puedas mantener. Podrías decir: “Me importas. No voy a darte dinero en efectivo. Puedo ayudarte a buscar otras opciones”. No necesitas convencerlo de que esté de acuerdo. Si la conversación deja de ser segura, aléjate y busca ayuda.',
    options: 'Cómo funciona el apoyo',
    timing: 'Los mensajes de Essential son para preguntas no urgentes, no un chat en vivo. No se garantiza un plazo fijo de respuesta. El video privado de Premier requiere programación y está sujeto a disponibilidad.',
    compare: 'Comparar membresías en Support',
    signedIn: 'Revisa las opciones para tu cuenta en Support. Abrir esta página no cambia tu membresía.',
    signedOut: 'Puedes leer esta guía sin suscribirte. Support muestra las opciones de membresía y los pasos para tu cuenta.',
    prices: 'Precios actuales de suscripción en la tienda',
  },
} as const;
