const en = {
  title: 'What brings you here today?', optional: 'Optional. Choose what fits now; you can change it later.',
  situations: { worried: 'I’m worried about someone', refuses: 'They refuse help', treatment: 'They’re in treatment or coming home', boundaries: 'I need help with boundaries', urgent: 'I need urgent help' },
  actions: { worried: 'Understand what you can influence', refuses: 'Find words for a calm conversation', treatment: 'Plan for coming home', boundaries: 'Choose one boundary', urgent: 'Open safety resources' },
  local: 'Your starting point and journey progress are saved only on this device for this account—not in the cloud. Clearing app data or changing devices removes them.',
  skip: 'Skip for now', change: 'Change starting point', continue: 'Continue', next: 'One possible next step',
  urgent: 'Free urgent support', disclaimer: 'This app is not monitored and does not send emergency alerts. In immediate danger, call your local emergency number. These contacts are for the U.S.; phone service is required.',
  journey: 'Your guided journey', resume: 'Continue your journey', start: 'Start your journey',
  steps: { understand: 'Understand', boundary: 'Boundary', practice: 'Practice', support: 'Support' },
  descriptions: { understand: 'Read one learning resource. Notice what you can influence and what is not yours to control.', boundary: 'Choose one limit you can follow through on. Write it in the boundaries tool.', practice: 'Choose a script and say it out loud, or adapt it to your own words.', support: 'Explore support options and choose one person or group you could reach out to.' },
  open: 'Open this step’s tool', complete: 'I’ve completed this step', done: 'Completed', finished: 'You’ve finished these four steps. You can revisit the tools whenever you need them.',
  pace: 'Go at your own pace. Opening a tool does not complete a step. Return here and mark it complete when you are ready.',
  reset: 'Clear starting point & restart journey', confirmReset: 'Clear this account’s starting point and journey progress on this device?', cancel: 'Cancel',
  retry: 'Try loading again', error: 'Could not load or save device data. Retry, or clear it to start again. Unsaved changes are not counted.', loading: 'Loading device progress…', back: 'Back',
  feedbackTitle: 'A next step, if helpful', feedbackNote: 'Based only on your saved answers—not a diagnosis or an AI assessment. You can leave this here for today.',
  feedback: {
    safety: ['You selected safety. Immediate support matters more than an exercise.', 'Open free safety resources'],
    overloaded: ['You reported low capacity and high pressure. Consider putting one nonessential task aside and asking someone you trust for practical help.', 'Explore support options'],
    connection: ['You asked for connection. A short message to someone you trust can be enough: “Could you check in with me today?”', 'Find support'],
    boundary: ['You asked for a boundary. Choose one limit about what you will do, rather than trying to control someone else.', 'Write one boundary'],
    plan: ['You asked for a plan. Pick one manageable step rather than solving everything today.', 'Open your guided journey'],
    rest: ['You asked for rest. If it is safe, pause one nonessential task and make room for water, food, or a quiet moment. You can say, “I need a break; we can talk later.”', 'Find words for taking space'],
    steady: ['You selected steady. You don’t need to do more. If you want, choose one idea to keep for a harder day.', 'Explore one learning resource'],
    lowMood: ['You reported a low mood. You do not have to solve everything today; consider reaching out to someone you trust.', 'Explore support options'],
  },
};
const es: typeof en = {
  title: '¿Qué te trae por aquí hoy?', optional: 'Es opcional. Elige lo que encaje ahora; puedes cambiarlo después.',
  situations: { worried: 'Me preocupa alguien', refuses: 'No acepta ayuda', treatment: 'Está en tratamiento o vuelve a casa', boundaries: 'Necesito ayuda con los límites', urgent: 'Necesito ayuda urgente' },
  actions: { worried: 'Comprende en qué puedes influir', refuses: 'Busca palabras para conversar con calma', treatment: 'Planifica la vuelta a casa', boundaries: 'Elige un límite', urgent: 'Abre recursos de seguridad' },
  local: 'Tu punto de partida y tu progreso se guardan solo en este dispositivo para esta cuenta, no en la nube. Se pierden al borrar los datos de la aplicación o cambiar de dispositivo.',
  skip: 'Omitir por ahora', change: 'Cambiar punto de partida', continue: 'Continuar', next: 'Un posible siguiente paso',
  urgent: 'Apoyo urgente gratuito', disclaimer: 'Esta aplicación no se supervisa ni envía alertas de emergencia. Ante un peligro inmediato, llama al número local de emergencias. Estos contactos son de EE. UU.; se necesita servicio telefónico.',
  journey: 'Tu recorrido guiado', resume: 'Continuar tu recorrido', start: 'Comenzar tu recorrido',
  steps: { understand: 'Comprender', boundary: 'Límite', practice: 'Practicar', support: 'Apoyo' },
  descriptions: { understand: 'Lee un recurso educativo. Observa en qué puedes influir y qué no te corresponde controlar.', boundary: 'Elige un límite que puedas mantener. Escríbelo en la herramienta de límites.', practice: 'Elige un guion y dilo en voz alta, o adáptalo con tus propias palabras.', support: 'Explora las opciones de apoyo y elige una persona o un grupo con quien podrías comunicarte.' },
  open: 'Abrir la herramienta de este paso', complete: 'He completado este paso', done: 'Completado', finished: 'Has terminado estos cuatro pasos. Puedes volver a las herramientas cuando lo necesites.',
  pace: 'Avanza a tu ritmo. Abrir una herramienta no completa un paso. Vuelve aquí y márcalo como completado cuando estés listo.',
  reset: 'Borrar punto de partida y reiniciar recorrido', confirmReset: '¿Borrar el punto de partida y el progreso de esta cuenta en este dispositivo?', cancel: 'Cancelar',
  retry: 'Intentar cargar de nuevo', error: 'No se pudieron cargar o guardar los datos del dispositivo. Reintenta o bórralos para empezar de nuevo. Los cambios sin guardar no se cuentan.', loading: 'Cargando el progreso del dispositivo…', back: 'Volver',
  feedbackTitle: 'Un siguiente paso, si te sirve', feedbackNote: 'Se basa solo en tus respuestas guardadas; no es un diagnóstico ni una evaluación de IA. Puedes dejarlo aquí por hoy.',
  feedback: {
    safety: ['Elegiste seguridad. El apoyo inmediato importa más que un ejercicio.', 'Abrir recursos gratuitos de seguridad'],
    overloaded: ['Indicaste poca capacidad y mucha presión. Considera posponer una tarea no esencial y pedir ayuda práctica a alguien de confianza.', 'Explorar opciones de apoyo'],
    connection: ['Pediste conexión. Puede bastar un mensaje breve a alguien de confianza: «¿Podrías preguntarme cómo estoy hoy?»', 'Buscar apoyo'],
    boundary: ['Pediste un límite. Elige uno sobre lo que tú harás, en lugar de intentar controlar a otra persona.', 'Escribir un límite'],
    plan: ['Pediste un plan. Elige un paso manejable en vez de resolverlo todo hoy.', 'Abrir tu recorrido guiado'],
    rest: ['Pediste descanso. Si es seguro, pausa una tarea no esencial y busca agua, comida o un momento de tranquilidad. Puedes decir: «Necesito un descanso; hablamos después».', 'Buscar palabras para pedir espacio'],
    steady: ['Elegiste estabilidad. No necesitas hacer más. Si quieres, elige una idea para un día más difícil.', 'Explorar un recurso educativo'],
    lowMood: ['Indicaste un ánimo bajo. No tienes que resolverlo todo hoy; considera hablar con alguien de confianza.', 'Explorar opciones de apoyo'],
  },
};
export function guidedStartCopy(language: string) { return language.toLowerCase().startsWith('es') ? es : en; }
