import type { Script } from '../api/types';

/**
 * Versioned production communication-script content.
 *
 * Two parallel libraries share the same ids, tags, and colors — English and
 * Spanish. Personalization, daily rotation, rehearsal counts, and the AI
 * practice partner all key off ids, so language switching is seamless.
 *
 * Each script carries:
 *  - comeback: one predicted pushback + a suggested reply (mini objection drill)
 *  - suggestedTemperament: pre-selects the practice partner's mood for this
 *    situation (omitted where AI practice isn't the right fit, e.g. talking
 *    to children or responding to self-harm).
 */

export const SCRIPTS: Script[] = [
  {
    id: 'script-money',
    tag: 'MONEY',
    tagBackgroundColor: '#fdf3e3',
    tagTextColor: '#9a6717',
    title: 'When they ask you for money',
    trySaying: "I love you, and I'm not able to give you money. I'm happy to bring you a meal or drive you to a meeting.",
    avoid: '"After everything we\'ve done for you?" — guilt invites a fight, not a change.',
    why: 'Offering non-cash support keeps the relationship open while protecting the boundary. Rehearse it out loud — twice.',
    comeback: {
      theySay: "So you'd rather see me starve?",
      youSay: "I'd rather feed you myself than fund what's hurting you. Dinner tonight — my treat.",
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-crisis',
    tag: 'CRISIS',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'The 2 AM phone call',
    trySaying: "I hear that you're hurting. I'll talk with you tomorrow when we're both rested. If this is an emergency, call 911.",
    avoid: 'Long late-night negotiations. Crisis hours favor manipulation over honesty.',
    why: "You're allowed to protect your sleep. A boundary stated calmly once is stronger than an argument repeated ten times.",
    comeback: {
      theySay: 'If you hang up, whatever happens is on you.',
      youSay: "I love you, and I'm hanging up now. If it's an emergency, call 911. I'll answer tomorrow.",
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-suspicion',
    tag: 'SUSPICION',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: "You suspect they've relapsed",
    trySaying: "I've noticed some changes and I'm concerned. I'm not accusing you — I'm telling you what I see because I love you.",
    avoid: 'Searching their room or phone before the conversation. Lead with observation, not evidence.',
    why: 'Describing behavior ("I noticed...") lands differently than labeling ("You\'re using again"). Log what you\'ve seen in the Tracker first.',
    comeback: {
      theySay: "So you're spying on me now?",
      youSay: "I'm not spying. I'm paying attention, because I love you. I'm telling you what I see.",
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-repair',
    tag: 'REPAIR',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'First visit after treatment begins',
    trySaying: "I'm proud of the work you're doing. I'm working on my side of this too.",
    avoid: 'Rehashing the intervention or past hurts in the first visits. There will be time — with a counselor present.',
    why: 'Early visits set the tone for the whole family system. Keep them short, warm, and future-facing.',
    comeback: {
      theySay: "You still don't trust me, do you?",
      youSay: "I'm here, aren't I? Trust grows back one visit at a time. This is one.",
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-denial',
    tag: 'DENIAL',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: "They say there's no problem",
    trySaying: "I'm not here to argue. I'm here to tell you what I've seen and how I feel. You don't have to agree right now.",
    avoid: '"How can you say that?!" — escalating the denial makes it a debate instead of a door.',
    why: 'Denial is a symptom, not a character flaw. Your job is to plant a seed, not win the argument. Say it once, clearly.',
    comeback: {
      theySay: "You're making this a way bigger deal than it is.",
      youSay: "Maybe. I'd love to be wrong. I'm still telling you what I've seen.",
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-anger',
    tag: 'ANGER',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'They get angry or defensive',
    trySaying: "I can see you're upset. That's okay. I'm not going anywhere. I'll be here when you're ready to talk.",
    avoid: 'Matching their volume or tone. Anger is designed to end the conversation.',
    why: 'A calm, consistent presence is more powerful than any argument. Let them see that your care is bigger than their reaction.',
    comeback: {
      theySay: 'Get out of my face!',
      youSay: "I'm going to step back. I'm not stepping away. When you're ready, I'm here.",
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-promises',
    tag: 'PROMISES',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: 'They promise to stop on their own',
    trySaying: "I want to believe you. I've believed you before. Today I'm asking for something different — a program, not a promise.",
    avoid: '"You\'ve said that a hundred times." — shaming the past closes off the future.',
    why: 'Addiction takes more than willpower. A personal promise without structure is hope without a plan. Ask for the structure.',
    comeback: {
      theySay: 'I swear, this time is different.',
      youSay: 'Then prove it in a program, where different has help. A promise plus structure — that I can believe in.',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-treatment-ask',
    tag: 'TREATMENT',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'Asking them to go to treatment today',
    trySaying: "I want you to go to treatment with me today. Not tomorrow. Today. I'll drive you.",
    avoid: '"Would you consider...?" or "Maybe when you\'re ready..." — conditional language gives them permission to delay.',
    why: 'The intervention moment is carefully chosen. Every hour of delay reduces the chance of a yes. The ask must be today.',
    comeback: {
      theySay: "I can't just drop everything today.",
      youSay: "Everything is already handled — we took care of the details. The bed is ready. All that's left is you.",
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-guilt',
    tag: 'GUILT',
    tagBackgroundColor: '#fdf3e3',
    tagTextColor: '#9a6717',
    title: 'They try to guilt-trip you',
    trySaying: "This conversation isn't about what I've done. I'll be accountable to my part — after you're in treatment.",
    avoid: 'Defending yourself or relitigating the past. Guilt is a deflection from the real question.',
    why: 'Guilt-shifting moves the conversation off the addiction and onto you. Acknowledge once, then redirect.',
    comeback: {
      theySay: 'You were never there for me. This is your fault too.',
      youSay: "I'll own my part — with a counselor, after you're in treatment. Today is about the help.",
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-enabling-family',
    tag: 'ENABLING',
    tagBackgroundColor: '#f0ecf8',
    tagTextColor: '#6b3fa0',
    title: 'A family member is enabling them',
    trySaying: "I know you love them and you're trying to help. I think we might be protecting them from the consequences that could actually save them.",
    avoid: '"You\'re the reason they\'re still using." — blame fractures the family before the conversation starts.',
    why: 'Enabling looks like help. You need this person as an ally, not an opponent. Name the pattern without naming a villain.',
    comeback: {
      theySay: 'You want me to just abandon my son?',
      youSay: "Never. I'm asking you to love him next to me — in a way the addiction can't use.",
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-relapse',
    tag: 'RELAPSE',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: "They've relapsed after treatment",
    trySaying: "I love you and I'm not giving up. Relapse is part of this for a lot of people. What do we do next?",
    avoid: '"I knew this would happen." — that phrase ends the conversation and confirms their shame.',
    why: 'A relapse is information, not a final verdict. How you respond in the first 24 hours shapes what comes next.',
    comeback: {
      theySay: "See? I told you I'd screw it up. I always do.",
      youSay: "A slip isn't the end of the story unless we stop here. What's the next right step — today?",
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-boundary-broken',
    tag: 'LIMITS',
    tagBackgroundColor: '#e8f4f8',
    tagTextColor: '#1a5a7a',
    title: "They've crossed a boundary you set",
    trySaying: "I told you this would change things, and I meant it. I still love you. And I won't [action] anymore.",
    avoid: 'Warning them again without following through. An empty consequence is worse than none.',
    why: "A boundary's power comes entirely from follow-through. The first time you hold it matters most.",
    comeback: {
      theySay: "One mistake and you're punishing me?",
      youSay: "It's not punishment. It's a promise I made to both of us — and I keep my promises now.",
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-phone-limits',
    tag: 'LIMITS',
    tagBackgroundColor: '#e8f4f8',
    tagTextColor: '#1a5a7a',
    title: 'They keep calling at all hours',
    trySaying: "I'm turning my phone off after 9 PM. I love you. If it's a true emergency, call 911.",
    avoid: '"Just this once" — there is no such thing.',
    why: 'Late-night calls are often designed to reach you when your resolve is lowest. Protecting your sleep protects your capacity to help.',
    comeback: {
      theySay: "So I can't even call my own mother?",
      youSay: "You can call me any day before nine. After nine, I'm resting — so I can love you well tomorrow.",
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-gathering',
    tag: 'FAMILY',
    tagBackgroundColor: '#f0ecf8',
    tagTextColor: '#6b3fa0',
    title: 'At a family gathering where they are drinking',
    trySaying: "I'm stepping out for a few minutes. I care about you — and I'm not willing to watch this right now.",
    avoid: 'A public confrontation. The room is not the right place, and shame makes people drink more, not less.',
    why: 'Removing yourself without drama keeps the focus on the issue, not a scene. You can have the real conversation later.',
    comeback: {
      theySay: "You're seriously making a scene about this?",
      youSay: "No scene. Just me, stepping out. We'll talk when it's the two of us.",
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-impaired',
    tag: 'SAFETY',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: "You discover they've been driving impaired",
    trySaying: "I need to tell you what I saw, and I need to tell you that I won't stay quiet about it again if it happens.",
    avoid: '"I\'m sure it was just that once." — silence is a vote for the behavior to continue.',
    why: 'This is a safety issue that extends beyond your family. Say it plainly, once, calmly.',
    comeback: {
      theySay: 'I was fine to drive. You worry too much.',
      youSay: '"Fine" is what luck looks like before it runs out. Next time I won\'t stay quiet — that\'s me loving you, not policing you.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-job',
    tag: 'CRISIS',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: "They're about to lose their job",
    trySaying: "I know work is falling apart and that's real. I also think the job might not be the main problem right now.",
    avoid: 'Helping cover for them at work. It delays the consequence that might be the turning point.',
    why: 'Job loss is painful but survivable. Keeping the secret keeps the addiction alive longer.',
    comeback: {
      theySay: "If I lose this job, it's because everyone's on my back instead of helping.",
      youSay: "I am helping — with the real problem. I'm not willing to help hide it.",
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-housing',
    tag: 'LIMITS',
    tagBackgroundColor: '#e8f4f8',
    tagTextColor: '#1a5a7a',
    title: 'Asking them to leave your home',
    trySaying: "I love you, and I won't keep you in this house while you're using. That's not changing. Let's talk about what help looks like.",
    avoid: "A deadline you won't follow through on. If you say Friday, mean Friday.",
    why: 'Your home should be a place of safety. That is non-negotiable. When they are in recovery, the conversation changes.',
    comeback: {
      theySay: "So you're throwing me out on the street?",
      youSay: "I'm offering you a bed in treatment today. Which door you take is your choice — but this one closes.",
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-milestone',
    tag: 'RECOVERY',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'Celebrating a sobriety milestone',
    trySaying: "I see what you're doing and I want you to know it matters to me. I'm proud of you.",
    avoid: '"Finally!" or making it about the past. Milestones are about now and forward.',
    why: 'Early recovery is fragile. Simple, sincere acknowledgment reinforces what they are building. Less is more.',
    comeback: {
      theySay: "It's just thirty days. It's not a big deal.",
      youSay: "Thirty days you built one at a time. It's a big deal to me.",
    },
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-fear',
    tag: 'RECOVERY',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'They express fear about going to treatment',
    trySaying: "I hear that you're scared. That's okay. I'll be scared with you. Let's go anyway.",
    avoid: '"It won\'t be that bad" — minimizing the fear doesn\'t land. Presence does.',
    why: 'Fear before treatment is almost universal. Meeting it with presence rather than reassurance is what helps.',
    comeback: {
      theySay: "What if I fail? What if it doesn't work?",
      youSay: "Then we'll know more than we know today — and you won't be finding out alone. Let's go.",
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-trust',
    tag: 'RECOVERY',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'Rebuilding trust after sobriety',
    trySaying: "I want to rebuild this with you. It's going to take time and that's honest. I'm not going anywhere.",
    avoid: '"But how do I know you won\'t..." — trust is rebuilt through behavior over time, not through promises.',
    why: 'Recovery is real. So is the damage. Both can be true. Start small and build forward without requiring proof upfront.',
    comeback: {
      theySay: "You'll never really forgive me, will you?",
      youSay: 'Forgiveness is happening — in installments. Every honest day makes the next one easier.',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-kids',
    tag: 'FAMILY',
    tagBackgroundColor: '#f0ecf8',
    tagTextColor: '#6b3fa0',
    title: 'Talking to children about addiction',
    trySaying: "Dad is sick in a way that makes him act differently sometimes. It's not your fault. We're getting him help.",
    avoid: 'Protecting kids with silence — they know more than we think, and silence itself is frightening.',
    why: 'Children are not too young to sense something is wrong. Naming it safely reduces shame and confusion.',
    comeback: {
      theySay: 'Is Daddy going to die?',
      youSay: "The helpers are working hard to keep him safe, sweetheart. And you can ask me anything, anytime. Always.",
    },
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-parents-disagree',
    tag: 'FAMILY',
    tagBackgroundColor: '#f0ecf8',
    tagTextColor: '#6b3fa0',
    title: 'Your parents disagree with the intervention',
    trySaying: "I know this feels extreme. I've watched this get worse for two years. I need you to trust me on this one.",
    avoid: '"You\'ve always protected him." — family history derails the current conversation.',
    why: 'Family systems pull toward the familiar, even when the familiar is harmful. Lead with what you have observed, not the past dynamic.',
    comeback: {
      theySay: "You're overreacting. He's just going through a phase.",
      youSay: "Two years isn't a phase. I've written down what I've seen — please read it before you decide.",
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-borrowed',
    tag: 'MONEY',
    tagBackgroundColor: '#fdf3e3',
    tagTextColor: '#9a6717',
    title: 'Money borrowed and never repaid',
    trySaying: "I'm not going to bring up the money anymore. What I am going to ask is that you get help.",
    avoid: 'Itemizing the debt. The money is gone. The goal is recovery, not repayment.',
    why: 'Connecting money to the addiction conversation muddles the message. Let the debt go as a strategy, not as a reward.',
    comeback: {
      theySay: "I'll pay you back, I swear — just help me out this one last time.",
      youSay: "The money's forgiven. The \"one last time\" is what I won't do anymore. Real help — that I'm offering.",
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-stolen',
    tag: 'CRISIS',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'You discovered they stole from family',
    trySaying: "I found out what happened and I need you to know that I know. It tells me how serious this has gotten.",
    avoid: 'Protecting them from the family members they stole from. The secret enables the behavior.',
    why: "Theft is a desperate act. It can be the moment that wakes everyone up — or the one that gets buried. Don't bury it.",
    comeback: {
      theySay: "You'd really turn on your own family over this?",
      youSay: "I'm not turning on you — I'm refusing to pretend. Treatment today changes what happens next.",
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-dui',
    tag: 'SAFETY',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'After a DUI or legal trouble',
    trySaying: "This is serious and I want to help — but not by making it go away. A lawyer won't fix what's underneath.",
    avoid: 'Hiring an attorney to minimize consequences before treatment is secured.',
    why: 'Legal consequences can be the most powerful lever for treatment. Using resources to escape them removes the pressure.',
    comeback: {
      theySay: "My lawyer says it'll get reduced. It's handled.",
      youSay: "The charge, maybe. The reason for it isn't. That's the part I care about.",
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-self-harm',
    tag: 'SAFETY',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'They threaten self-harm',
    trySaying: "I'm taking this seriously and I'm calling 988 right now. I'll stay with you.",
    avoid: 'Treating it as manipulation without evaluation — even if it has been before, it must be addressed every time.',
    why: 'Addiction and mental health overlap. A threat of self-harm always requires a response, not a judgment call.',
    comeback: {
      theySay: "Forget it. I didn't mean it.",
      youSay: "I heard it, and I take you seriously every time. We're making the call together.",
    },
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-first-convo',
    tag: 'CONVERSATION',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: 'The first time you bring it up',
    trySaying: "I've been wanting to say this for a while and I care about you too much to stay quiet. I'm worried.",
    avoid: '"I think you might have a problem..." — the hedge invites denial. Say what you see.',
    why: "The first conversation plants a seed. It doesn't need to fix everything. It needs to be honest.",
    comeback: {
      theySay: 'Where is this coming from all of a sudden?',
      youSay: "It's not sudden — I've been carrying it a while. I care too much to keep carrying it silently.",
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-negotiate',
    tag: 'TREATMENT',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'They try to negotiate alternatives to treatment',
    trySaying: "I hear you. And today I'm only here for one thing. Treatment. That's the only conversation I'm here for.",
    avoid: 'Engaging with the counter-offer. Every alternative they propose is a delay tactic.',
    why: '"I\'ll go to AA" or "I\'ll see a therapist" can be real commitments — after treatment, not instead of it.',
    comeback: {
      theySay: "I'll do outpatient, I'll do meetings — just not that place.",
      youSay: "After treatment, all of that helps. Instead of treatment, none of it ever has. Today it's this.",
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  // ---- New situations ----
  {
    id: 'script-overdose-scare',
    tag: 'SAFETY',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'The morning after an overdose scare',
    trySaying: "I thought I was losing you last night. I won't pretend that didn't happen. There's help available today — I'm asking you to take it.",
    avoid: "Letting relief turn into silence. The scare fades fast for them — this morning is the widest door you'll get.",
    why: 'Willingness peaks in the hours after a crisis and shrinks by the day. Speak while the truth of last night is still in the room.',
    comeback: {
      theySay: "It wasn't that bad. Everyone's overreacting.",
      youSay: "I was there. I know what I saw, and I won't unsee it. The help is ready today — will you take it?",
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-come-home-call',
    tag: 'TREATMENT',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'They call from treatment wanting to come home',
    trySaying: "I'm so proud of you. Stay. The hardest days are the ones that count the most. We'll see you on visiting day.",
    avoid: 'Negotiating an exit or promising to "look into it." Detox and early treatment talk — this call is expected, and it passes.',
    why: 'Nearly every family gets this call in the first two weeks. One loving, identical answer — agreed on in advance — is what carries them through it.',
    comeback: {
      theySay: "You don't understand what it's like in here. If you loved me, you'd come get me.",
      youSay: "I love you too much to rescue you from the thing that's saving you. Stay. We'll be there Sunday.",
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-sit-down',
    tag: 'CONVERSATION',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: 'Asking them to sit down and listen',
    trySaying: "We're all here because we love you. We're asking you to sit with us for a few minutes and just listen.",
    avoid: 'Explaining, apologizing, or debating the setup. Two warm sentences, then the letters begin.',
    why: 'The opening seconds decide whether they stay in the room. Warmth and brevity beat any speech. This is the chairperson\'s line — rehearse it until it\'s calm.',
    comeback: {
      theySay: 'What is this — an ambush?',
      youSay: "It's the people who love you most, in one room, telling the truth. Please sit with us. Just listen.",
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-no-more-covering',
    tag: 'ENABLING',
    tagBackgroundColor: '#f0ecf8',
    tagTextColor: '#6b3fa0',
    title: "Telling them you're done covering for them",
    trySaying: "I've been making excuses for you — to work, to family, to myself. I love you, and I'm not willing to lie for you anymore.",
    avoid: 'Announcing it as a threat or an ultimatum delivered in anger. This is a boundary about your own integrity, stated calmly.',
    why: 'Every excuse you make absorbs a consequence that could have counted. Ending the cover story is one of the most loving boundaries there is.',
    comeback: {
      theySay: "So you're going to embarrass me in front of everyone?",
      youSay: "Your choices tell their own story — I'm just done telling a different one. And I'm right here the moment you want help.",
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-good-day',
    tag: 'CONVERSATION',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: 'Bringing it up on a good day',
    trySaying: "Today's been a good day — and that's exactly why I want to talk now, not in a crisis. I'm worried, and I want us to get ahead of this together.",
    avoid: "Waiting for the next blow-up to talk. Crisis conversations start with adrenaline; good-day conversations start with love.",
    why: 'The best conversations about addiction often happen when nothing is on fire. Calm moments lower defenses — theirs and yours.',
    comeback: {
      theySay: 'Why would you ruin a nice day with this?',
      youSay: "Because I want a hundred more days like this one. That's the whole point.",
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-after-no',
    tag: 'LIMITS',
    tagBackgroundColor: '#e8f4f8',
    tagTextColor: '#1a5a7a',
    title: 'The day after they said no',
    trySaying: "Yesterday you said no, and I heard you. Nothing about my love has changed — and nothing about what I said has changed either. The help stays ready.",
    avoid: 'Reopening the debate or softening the boundaries to make peace. A no doesn\'t reset what the family said with one voice.',
    why: 'Most delayed yeses arrive within weeks — when the boundaries hold. The day after a no is when families either stand or fold. Stand, warmly.',
    comeback: {
      theySay: 'Are you going to bring this up every single day now?',
      youSay: "No. I said what's true and I won't hound you with it. But I won't act like it wasn't said, either.",
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
];

/** Spanish library — same ids, tags, and colors; content culturally adapted. */
export const SCRIPTS_ES: Script[] = [
  {
    id: 'script-money',
    tag: 'MONEY',
    tagBackgroundColor: '#fdf3e3',
    tagTextColor: '#9a6717',
    title: 'Cuando te pide dinero',
    trySaying: 'Te amo, y no voy a darte dinero. Con gusto te llevo algo de comer o te acompaño a una reunión.',
    avoid: '"¿Después de todo lo que hemos hecho por ti?" — la culpa invita a una pelea, no a un cambio.',
    why: 'Ofrecer apoyo que no sea dinero mantiene la relación abierta mientras proteges el límite. Ensáyalo en voz alta — dos veces.',
    comeback: {
      theySay: '¿Entonces prefieres verme pasar hambre?',
      youSay: 'Prefiero darte de comer yo mismo antes que financiar lo que te está destruyendo. Cena esta noche — yo invito.',
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-crisis',
    tag: 'CRISIS',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'La llamada de las 2 de la mañana',
    trySaying: 'Escucho que estás sufriendo. Hablamos mañana, cuando los dos hayamos descansado. Si es una emergencia, llama al 911.',
    avoid: 'Negociaciones largas de madrugada. Las horas de crisis favorecen la manipulación, no la honestidad.',
    why: 'Tienes derecho a proteger tu descanso. Un límite dicho con calma una vez vale más que una discusión repetida diez veces.',
    comeback: {
      theySay: 'Si me cuelgas, lo que pase será tu culpa.',
      youSay: 'Te amo, y voy a colgar ahora. Si es una emergencia, llama al 911. Mañana contesto.',
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-suspicion',
    tag: 'SUSPICION',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: 'Sospechas que recayó',
    trySaying: 'He notado algunos cambios y estoy preocupado. No te estoy acusando — te digo lo que veo porque te amo.',
    avoid: 'Registrar su cuarto o su teléfono antes de conversar. Empieza por lo que has observado, no por evidencias.',
    why: 'Describir la conducta ("he notado...") llega distinto que etiquetar ("estás usando otra vez"). Anota primero lo que has visto en el Registro.',
    comeback: {
      theySay: '¿Ahora me estás espiando?',
      youSay: 'No te espío. Te presto atención, porque te amo. Y te digo lo que veo.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-repair',
    tag: 'REPAIR',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'Primera visita al comenzar el tratamiento',
    trySaying: 'Estoy orgulloso del trabajo que estás haciendo. Yo también estoy trabajando en mi parte.',
    avoid: 'Revivir la intervención o las heridas del pasado en las primeras visitas. Habrá tiempo — con un consejero presente.',
    why: 'Las primeras visitas marcan el tono para toda la familia. Que sean cortas, cálidas y mirando hacia adelante.',
    comeback: {
      theySay: 'Todavía no confías en mí, ¿verdad?',
      youSay: 'Aquí estoy, ¿no? La confianza vuelve a crecer visita por visita. Esta es una.',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-denial',
    tag: 'DENIAL',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: 'Dice que no hay ningún problema',
    trySaying: 'No vine a discutir. Vine a decirte lo que he visto y lo que siento. No tienes que estar de acuerdo ahora.',
    avoid: '"¡¿Cómo puedes decir eso?!" — escalar la negación la convierte en debate en lugar de una puerta.',
    why: 'La negación es un síntoma, no un defecto de carácter. Tu tarea es sembrar una semilla, no ganar la discusión. Dilo una vez, con claridad.',
    comeback: {
      theySay: 'Estás haciendo esto mucho más grande de lo que es.',
      youSay: 'Puede ser. Me encantaría estar equivocado. Aun así, te digo lo que he visto.',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-anger',
    tag: 'ANGER',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'Se enoja o se pone a la defensiva',
    trySaying: 'Veo que estás molesto. Está bien. No me voy a ninguna parte. Aquí estaré cuando quieras hablar.',
    avoid: 'Igualar su volumen o su tono. El enojo está diseñado para terminar la conversación.',
    why: 'Una presencia calmada y constante es más poderosa que cualquier argumento. Que vea que tu cariño es más grande que su reacción.',
    comeback: {
      theySay: '¡Déjame en paz!',
      youSay: 'Voy a darte espacio. Pero no voy a desaparecer. Cuando estés listo, aquí estoy.',
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-promises',
    tag: 'PROMISES',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: 'Promete dejarlo por su cuenta',
    trySaying: 'Quiero creerte. Te he creído antes. Hoy te pido algo distinto — un programa, no una promesa.',
    avoid: '"Eso lo has dicho cien veces." — avergonzar el pasado cierra la puerta del futuro.',
    why: 'La adicción requiere más que fuerza de voluntad. Una promesa sin estructura es esperanza sin plan. Pide la estructura.',
    comeback: {
      theySay: 'Te lo juro, esta vez es diferente.',
      youSay: 'Entonces demuéstralo en un programa, donde lo diferente tiene apoyo. Una promesa con estructura — en eso sí puedo creer.',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-treatment-ask',
    tag: 'TREATMENT',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'Pedirle que vaya a tratamiento hoy',
    trySaying: 'Quiero que vayas a tratamiento conmigo hoy. No mañana. Hoy. Yo te llevo.',
    avoid: '"¿Considerarías...?" o "Quizás cuando estés listo..." — el lenguaje condicional le da permiso de aplazar.',
    why: 'El momento de la intervención se elige con cuidado. Cada hora de espera reduce la posibilidad de un sí. La petición es hoy.',
    comeback: {
      theySay: 'No puedo dejarlo todo botado así como así.',
      youSay: 'Todo está resuelto — nos encargamos de los detalles. La cama está lista. Solo faltas tú.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-guilt',
    tag: 'GUILT',
    tagBackgroundColor: '#fdf3e3',
    tagTextColor: '#9a6717',
    title: 'Intenta hacerte sentir culpable',
    trySaying: 'Esta conversación no es sobre lo que yo he hecho. Voy a responder por mi parte — después de que estés en tratamiento.',
    avoid: 'Defenderte o volver a juzgar el pasado. La culpa es una distracción de la pregunta real.',
    why: 'Trasladar la culpa mueve la conversación de la adicción hacia ti. Reconoce una vez, y redirige.',
    comeback: {
      theySay: 'Tú nunca estuviste para mí. Esto también es tu culpa.',
      youSay: 'Voy a asumir mi parte — con un consejero, cuando estés en tratamiento. Hoy se trata de la ayuda.',
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-enabling-family',
    tag: 'ENABLING',
    tagBackgroundColor: '#f0ecf8',
    tagTextColor: '#6b3fa0',
    title: 'Un familiar lo está facilitando',
    trySaying: 'Sé que lo amas y que intentas ayudarlo. Creo que quizás lo estamos protegiendo de las consecuencias que podrían salvarlo.',
    avoid: '"Por tu culpa sigue usando." — la culpa fractura a la familia antes de que empiece la conversación.',
    why: 'Facilitar se parece a ayudar. Necesitas a esta persona como aliada, no como oponente. Nombra el patrón sin nombrar a un villano.',
    comeback: {
      theySay: '¿Quieres que abandone a mi hijo?',
      youSay: 'Jamás. Te pido que lo amemos juntos — de una forma que la adicción no pueda usar.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-relapse',
    tag: 'RELAPSE',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'Recayó después del tratamiento',
    trySaying: 'Te amo y no me rindo. La recaída es parte del camino para muchas personas. ¿Qué hacemos ahora?',
    avoid: '"Sabía que esto iba a pasar." — esa frase termina la conversación y confirma su vergüenza.',
    why: 'Una recaída es información, no un veredicto final. Cómo respondas en las primeras 24 horas define lo que sigue.',
    comeback: {
      theySay: '¿Ves? Te dije que lo iba a arruinar. Siempre lo arruino.',
      youSay: 'Un tropiezo no es el final de la historia, a menos que nos detengamos aquí. ¿Cuál es el siguiente paso — hoy?',
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-boundary-broken',
    tag: 'LIMITS',
    tagBackgroundColor: '#e8f4f8',
    tagTextColor: '#1a5a7a',
    title: 'Cruzó un límite que pusiste',
    trySaying: 'Te dije que esto cambiaría las cosas, y lo dije en serio. Te sigo amando. Y no voy a [acción] más.',
    avoid: 'Advertirle otra vez sin cumplir. Una consecuencia vacía es peor que ninguna.',
    why: 'El poder de un límite está por completo en cumplirlo. La primera vez que lo sostienes es la que más importa.',
    comeback: {
      theySay: '¿Un error y ya me estás castigando?',
      youSay: 'No es castigo. Es una promesa que me hice a mí y a ti — y ahora yo cumplo mis promesas.',
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-phone-limits',
    tag: 'LIMITS',
    tagBackgroundColor: '#e8f4f8',
    tagTextColor: '#1a5a7a',
    title: 'Llama a todas horas',
    trySaying: 'Voy a apagar mi teléfono después de las 9. Te amo. Si es una verdadera emergencia, llama al 911.',
    avoid: '"Solo por esta vez" — eso no existe.',
    why: 'Las llamadas de madrugada suelen buscar el momento en que tu resistencia está más baja. Proteger tu sueño protege tu capacidad de ayudar.',
    comeback: {
      theySay: '¿Entonces ya ni puedo llamar a mi propia madre?',
      youSay: 'Puedes llamarme cualquier día antes de las nueve. Después de las nueve descanso — para poder quererte bien mañana.',
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-gathering',
    tag: 'FAMILY',
    tagBackgroundColor: '#f0ecf8',
    tagTextColor: '#6b3fa0',
    title: 'En una reunión familiar donde está bebiendo',
    trySaying: 'Voy a salir unos minutos. Me importas — y no estoy dispuesto a ver esto ahora.',
    avoid: 'Una confrontación pública. La sala no es el lugar, y la vergüenza hace que la gente beba más, no menos.',
    why: 'Retirarte sin drama mantiene el foco en el problema, no en una escena. La conversación real puede darse después.',
    comeback: {
      theySay: '¿En serio vas a armar un drama por esto?',
      youSay: 'Sin drama. Solo salgo un momento. Hablamos cuando estemos tú y yo.',
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-impaired',
    tag: 'SAFETY',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'Descubres que manejó bajo los efectos',
    trySaying: 'Necesito decirte lo que vi, y necesito decirte que no volveré a quedarme callado si vuelve a pasar.',
    avoid: '"Seguro fue solo esa vez." — el silencio es un voto para que la conducta continúe.',
    why: 'Es un tema de seguridad que va más allá de tu familia. Dilo claro, una vez, con calma.',
    comeback: {
      theySay: 'Estaba bien para manejar. Te preocupas demasiado.',
      youSay: '"Bien" es como se ve la suerte antes de acabarse. La próxima vez no me quedo callado — eso es quererte, no vigilarte.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-job',
    tag: 'CRISIS',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'Está por perder su trabajo',
    trySaying: 'Sé que el trabajo se está derrumbando y eso es real. También creo que el trabajo no es el problema principal ahora.',
    avoid: 'Ayudar a encubrirlo en el trabajo. Aplaza la consecuencia que podría ser el punto de inflexión.',
    why: 'Perder un trabajo duele, pero se sobrevive. Guardar el secreto mantiene viva la adicción más tiempo.',
    comeback: {
      theySay: 'Si pierdo este trabajo será porque todos me presionan en vez de ayudarme.',
      youSay: 'Sí estoy ayudando — con el problema de verdad. Lo que no voy a hacer es ayudar a esconderlo.',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-housing',
    tag: 'LIMITS',
    tagBackgroundColor: '#e8f4f8',
    tagTextColor: '#1a5a7a',
    title: 'Pedirle que deje tu casa',
    trySaying: 'Te amo, y no voy a tenerte en esta casa mientras estés usando. Eso no va a cambiar. Hablemos de cómo se ve la ayuda.',
    avoid: 'Un plazo que no vas a cumplir. Si dices el viernes, que sea el viernes.',
    why: 'Tu casa debe ser un lugar seguro. Eso no es negociable. Cuando esté en recuperación, la conversación cambia.',
    comeback: {
      theySay: '¿Entonces me vas a echar a la calle?',
      youSay: 'Te estoy ofreciendo una cama en tratamiento hoy. Cuál puerta tomas es tu decisión — pero esta se cierra.',
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-milestone',
    tag: 'RECOVERY',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'Celebrar un hito de sobriedad',
    trySaying: 'Veo lo que estás haciendo y quiero que sepas que me importa. Estoy orgulloso de ti.',
    avoid: '"¡Por fin!" o hacerlo sobre el pasado. Los hitos son sobre el ahora y lo que viene.',
    why: 'La recuperación temprana es frágil. Un reconocimiento simple y sincero refuerza lo que está construyendo. Menos es más.',
    comeback: {
      theySay: 'Son solo treinta días. No es para tanto.',
      youSay: 'Treinta días que construiste uno por uno. Para mí es enorme.',
    },
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-fear',
    tag: 'RECOVERY',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'Expresa miedo de ir a tratamiento',
    trySaying: 'Escucho que tienes miedo. Está bien. Yo tendré miedo contigo. Vamos de todos modos.',
    avoid: '"No va a ser tan malo" — minimizar el miedo no llega. La presencia sí.',
    why: 'El miedo antes del tratamiento es casi universal. Recibirlo con presencia y no con consuelo vacío es lo que ayuda.',
    comeback: {
      theySay: '¿Y si fracaso? ¿Y si no funciona?',
      youSay: 'Entonces sabremos más de lo que sabemos hoy — y no lo vas a descubrir solo. Vamos.',
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-trust',
    tag: 'RECOVERY',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'Reconstruir la confianza en la sobriedad',
    trySaying: 'Quiero reconstruir esto contigo. Va a tomar tiempo, y eso es lo honesto. No me voy a ninguna parte.',
    avoid: '"¿Pero cómo sé que no vas a...?" — la confianza se reconstruye con conducta a lo largo del tiempo, no con promesas.',
    why: 'La recuperación es real. El daño también. Las dos cosas pueden ser ciertas. Empieza pequeño y avanza sin exigir pruebas por adelantado.',
    comeback: {
      theySay: 'Nunca me vas a perdonar de verdad, ¿cierto?',
      youSay: 'El perdón está sucediendo — en abonos. Cada día honesto hace más fácil el siguiente.',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-kids',
    tag: 'FAMILY',
    tagBackgroundColor: '#f0ecf8',
    tagTextColor: '#6b3fa0',
    title: 'Hablar con los niños sobre la adicción',
    trySaying: 'Papá está enfermo de una forma que a veces lo hace actuar diferente. No es tu culpa. Le estamos consiguiendo ayuda.',
    avoid: 'Proteger a los niños con silencio — saben más de lo que creemos, y el silencio en sí mismo asusta.',
    why: 'Los niños no son demasiado pequeños para sentir que algo anda mal. Nombrarlo con cuidado reduce la vergüenza y la confusión.',
    comeback: {
      theySay: '¿Papi se va a morir?',
      youSay: 'Los que lo cuidan están trabajando muy duro para protegerlo, mi amor. Y tú puedes preguntarme lo que sea, cuando sea. Siempre.',
    },
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-parents-disagree',
    tag: 'FAMILY',
    tagBackgroundColor: '#f0ecf8',
    tagTextColor: '#6b3fa0',
    title: 'Tus padres no están de acuerdo con la intervención',
    trySaying: 'Sé que esto se siente extremo. Llevo dos años viendo cómo empeora. Necesito que confíes en mí en esto.',
    avoid: '"Tú siempre lo has protegido." — la historia familiar descarrila la conversación actual.',
    why: 'Los sistemas familiares tiran hacia lo conocido, aun cuando lo conocido hace daño. Habla desde lo que has observado, no desde la vieja dinámica.',
    comeback: {
      theySay: 'Estás exagerando. Es solo una etapa.',
      youSay: 'Dos años no son una etapa. Escribí lo que he visto — por favor léelo antes de decidir.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-borrowed',
    tag: 'MONEY',
    tagBackgroundColor: '#fdf3e3',
    tagTextColor: '#9a6717',
    title: 'Dinero prestado que nunca devolvió',
    trySaying: 'No voy a volver a mencionar el dinero. Lo que sí voy a pedirte es que aceptes ayuda.',
    avoid: 'Detallar la deuda. El dinero ya no está. La meta es la recuperación, no el reembolso.',
    why: 'Mezclar el dinero con la conversación de la adicción enreda el mensaje. Soltar la deuda es una estrategia, no un premio.',
    comeback: {
      theySay: 'Te lo voy a pagar, lo juro — solo ayúdame esta última vez.',
      youSay: 'El dinero está perdonado. La "última vez" es lo que ya no voy a hacer. Ayuda de verdad — eso sí te lo ofrezco.',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-stolen',
    tag: 'CRISIS',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'Descubriste que robó a la familia',
    trySaying: 'Me enteré de lo que pasó y necesito que sepas que lo sé. Me dice lo serio que se ha vuelto esto.',
    avoid: 'Protegerlo de los familiares a los que les robó. El secreto alimenta la conducta.',
    why: 'Robar es un acto de desesperación. Puede ser el momento que despierte a todos — o el que se entierra. No lo entierres.',
    comeback: {
      theySay: '¿De verdad te pondrías en contra de tu propia familia por esto?',
      youSay: 'No estoy en tu contra — me niego a fingir. Tratamiento hoy cambia lo que sigue.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-dui',
    tag: 'SAFETY',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'Después de un DUI o problemas legales',
    trySaying: 'Esto es serio y quiero ayudar — pero no haciéndolo desaparecer. Un abogado no arregla lo que hay debajo.',
    avoid: 'Contratar a un abogado para minimizar consecuencias antes de asegurar el tratamiento.',
    why: 'Las consecuencias legales pueden ser la palanca más poderosa hacia el tratamiento. Usar recursos para escapar de ellas quita la presión.',
    comeback: {
      theySay: 'Mi abogado dice que lo van a reducir. Está resuelto.',
      youSay: 'El cargo, quizás. La razón detrás, no. Esa es la parte que me importa.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-self-harm',
    tag: 'SAFETY',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'Amenaza con hacerse daño',
    trySaying: 'Esto lo tomo en serio y voy a llamar al 988 ahora mismo. Me quedo contigo.',
    avoid: 'Tratarlo como manipulación sin evaluarlo — aunque lo haya sido antes, debe atenderse cada vez.',
    why: 'La adicción y la salud mental se cruzan. Una amenaza de hacerse daño siempre requiere una respuesta, no un juicio.',
    comeback: {
      theySay: 'Olvídalo. No lo dije en serio.',
      youSay: 'Lo escuché, y te tomo en serio todas las veces. Hacemos la llamada juntos.',
    },
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-first-convo',
    tag: 'CONVERSATION',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: 'La primera vez que lo mencionas',
    trySaying: 'Hace tiempo quiero decirte esto, y me importas demasiado para seguir callado. Estoy preocupado.',
    avoid: '"Creo que quizás tengas un problema..." — la vacilación invita a la negación. Di lo que ves.',
    why: 'La primera conversación siembra una semilla. No tiene que arreglarlo todo. Tiene que ser honesta.',
    comeback: {
      theySay: '¿Y esto de dónde sale tan de repente?',
      youSay: 'No es repentino — lo llevo cargando un buen rato. Me importas demasiado para seguir cargándolo en silencio.',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-negotiate',
    tag: 'TREATMENT',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'Intenta negociar alternativas al tratamiento',
    trySaying: 'Te escucho. Y hoy vine por una sola cosa. Tratamiento. Esa es la única conversación que vine a tener.',
    avoid: 'Entrar en la contraoferta. Cada alternativa que propone es una táctica para aplazar.',
    why: '"Voy a ir a AA" o "voy a ver a un terapeuta" pueden ser compromisos reales — después del tratamiento, no en su lugar.',
    comeback: {
      theySay: 'Hago ambulatorio, voy a reuniones — pero a ese lugar no.',
      youSay: 'Después del tratamiento, todo eso ayuda. En lugar del tratamiento, nunca ha ayudado. Hoy es esto.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  // ---- Situaciones nuevas ----
  {
    id: 'script-overdose-scare',
    tag: 'SAFETY',
    tagBackgroundColor: '#fbeae7',
    tagTextColor: '#c4604f',
    title: 'La mañana después de un susto de sobredosis',
    trySaying: 'Anoche pensé que te perdía. No voy a fingir que no pasó. Hay ayuda disponible hoy — te pido que la tomes.',
    avoid: 'Dejar que el alivio se convierta en silencio. Para ellos el susto se desvanece rápido — esta mañana es la puerta más abierta que vas a tener.',
    why: 'La disposición llega a su punto máximo en las horas después de una crisis y se encoge día a día. Habla mientras la verdad de anoche sigue en la sala.',
    comeback: {
      theySay: 'No fue para tanto. Todos están exagerando.',
      youSay: 'Yo estuve ahí. Sé lo que vi, y no puedo dejar de verlo. La ayuda está lista hoy — ¿la tomas?',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-come-home-call',
    tag: 'TREATMENT',
    tagBackgroundColor: '#e9f2ec',
    tagTextColor: '#4d7c5f',
    title: 'Llama del tratamiento y quiere volver a casa',
    trySaying: 'Estoy muy orgulloso de ti. Quédate. Los días más difíciles son los que más cuentan. Nos vemos el día de visita.',
    avoid: 'Negociar una salida o prometer que "lo vas a pensar". La desintoxicación habla así — esta llamada es esperada, y pasa.',
    why: 'Casi todas las familias reciben esta llamada en las primeras dos semanas. Una sola respuesta amorosa e idéntica — acordada de antemano — es lo que los sostiene.',
    comeback: {
      theySay: 'No entiendes cómo es esto aquí. Si me quisieras, vendrías por mí.',
      youSay: 'Te quiero demasiado para rescatarte de lo que te está salvando. Quédate. Ahí estaremos el domingo.',
    },
    suggestedTemperament: 'tearful',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-sit-down',
    tag: 'CONVERSATION',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: 'Pedirle que se siente y escuche',
    trySaying: 'Todos estamos aquí porque te amamos. Te pedimos que te sientes con nosotros unos minutos y solo escuches.',
    avoid: 'Explicar, disculparte o debatir el formato. Dos frases cálidas, y empiezan las cartas.',
    why: 'Los primeros segundos deciden si se queda en la sala. La calidez y la brevedad ganan a cualquier discurso. Esta es la línea de quien preside — ensáyala hasta que salga en calma.',
    comeback: {
      theySay: '¿Qué es esto — una emboscada?',
      youSay: 'Es la gente que más te ama, en una sola sala, diciendo la verdad. Por favor siéntate con nosotros. Solo escucha.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-no-more-covering',
    tag: 'ENABLING',
    tagBackgroundColor: '#f0ecf8',
    tagTextColor: '#6b3fa0',
    title: 'Decirle que ya no vas a encubrirlo',
    trySaying: 'He estado poniendo excusas por ti — en el trabajo, con la familia, conmigo mismo. Te amo, y no estoy dispuesto a seguir mintiendo por ti.',
    avoid: 'Anunciarlo como amenaza o ultimátum en un momento de rabia. Es un límite sobre tu propia integridad, dicho con calma.',
    why: 'Cada excusa que pones absorbe una consecuencia que pudo haber contado. Terminar con el encubrimiento es uno de los límites más amorosos que existen.',
    comeback: {
      theySay: '¿Entonces me vas a avergonzar delante de todos?',
      youSay: 'Tus decisiones cuentan su propia historia — yo solo dejé de contar una diferente. Y aquí estoy en el momento en que quieras ayuda.',
    },
    suggestedTemperament: 'volatile',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-good-day',
    tag: 'CONVERSATION',
    tagBackgroundColor: '#e8eef6',
    tagTextColor: '#1a365d',
    title: 'Hablarlo en un buen día',
    trySaying: 'Hoy ha sido un buen día — y justo por eso quiero hablar ahora, no en una crisis. Estoy preocupado, y quiero que nos adelantemos a esto juntos.',
    avoid: 'Esperar a la próxima explosión para hablar. Las conversaciones en crisis empiezan con adrenalina; las de un buen día empiezan con amor.',
    why: 'Las mejores conversaciones sobre la adicción suelen darse cuando nada está en llamas. Los momentos de calma bajan las defensas — las suyas y las tuyas.',
    comeback: {
      theySay: '¿Por qué arruinas un día bonito con esto?',
      youSay: 'Porque quiero cien días más como este. Ese es exactamente el punto.',
    },
    suggestedTemperament: 'guarded',
    isCustom: false,
    requestedFromCoachId: null,
  },
  {
    id: 'script-after-no',
    tag: 'LIMITS',
    tagBackgroundColor: '#e8f4f8',
    tagTextColor: '#1a5a7a',
    title: 'El día después de que dijo que no',
    trySaying: 'Ayer dijiste que no, y te escuché. Nada de mi amor ha cambiado — y nada de lo que dije ha cambiado tampoco. La ayuda sigue lista.',
    avoid: 'Reabrir el debate o suavizar los límites para hacer las paces. Un no no borra lo que la familia dijo con una sola voz.',
    why: 'La mayoría de los síes tardíos llegan en unas semanas — cuando los límites se sostienen. El día después de un no es cuando las familias se mantienen firmes o se doblan. Mantente firme, con cariño.',
    comeback: {
      theySay: '¿Me vas a recordar esto todos los días o qué?',
      youSay: 'No. Dije lo que es verdad y no te voy a perseguir con eso. Pero tampoco voy a actuar como si no se hubiera dicho.',
    },
    suggestedTemperament: 'defensive',
    isCustom: false,
    requestedFromCoachId: null,
  },
];

// Rotation: three scripts per day-slot, mixed so each day pairs a heavier
// situation with a lighter one. Every script appears within the 12-day
// cycle (two high-utility ones appear twice); no repeats within a day.
const DAILY_SCRIPT_SETS: [string, string, string][] = [
  ['script-money', 'script-crisis', 'script-good-day'],                    // Day 0
  ['script-first-convo', 'script-denial', 'script-phone-limits'],          // Day 1
  ['script-relapse', 'script-repair', 'script-gathering'],                 // Day 2
  ['script-treatment-ask', 'script-promises', 'script-milestone'],         // Day 3
  ['script-boundary-broken', 'script-guilt', 'script-job'],                // Day 4
  ['script-come-home-call', 'script-enabling-family', 'script-trust'],     // Day 5
  ['script-suspicion', 'script-borrowed', 'script-kids'],                  // Day 6
  ['script-overdose-scare', 'script-anger', 'script-housing'],             // Day 7
  ['script-sit-down', 'script-negotiate', 'script-fear'],                  // Day 8
  ['script-no-more-covering', 'script-stolen', 'script-parents-disagree'], // Day 9
  ['script-impaired', 'script-dui', 'script-after-no'],                    // Day 10
  ['script-first-convo', 'script-self-harm', 'script-money'],              // Day 11
];

// Curated shelves for browsing. Every tag maps to exactly one shelf, so the
// full library reads as a short index instead of a wall of 34 cards. Crisis
// stays first regardless of personalization — the user who needs those
// scripts is the one who can't afford to hunt for them.
export const SCRIPT_CATEGORIES: { key: string; tags: string[] }[] = [
  { key: 'crisis', tags: ['CRISIS', 'SAFETY'] },
  { key: 'boundaries', tags: ['LIMITS', 'MONEY', 'ENABLING'] },
  { key: 'treatment', tags: ['TREATMENT', 'DENIAL', 'PROMISES'] },
  { key: 'emotions', tags: ['ANGER', 'GUILT', 'SUSPICION'] },
  { key: 'recovery', tags: ['RECOVERY', 'REPAIR', 'RELAPSE'] },
  { key: 'everyday', tags: ['CONVERSATION', 'FAMILY'] },
];

function libraryFor(language?: string): Script[] {
  return language?.startsWith('es') ? SCRIPTS_ES : SCRIPTS;
}

export function getScripts(language?: string): Script[] {
  return libraryFor(language);
}

export function getDailyScripts(daySlot: number, language?: string): Script[] {
  const library = libraryFor(language);
  const byId = new Map(library.map((s) => [s.id, s]));
  const ids = DAILY_SCRIPT_SETS[daySlot % DAILY_SCRIPT_SETS.length] ?? DAILY_SCRIPT_SETS[0];
  return ids.map((id) => byId.get(id)).filter(Boolean) as Script[];
}
